FROM debian:13-slim AS build

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update -yq && apt-get install -yq build-essential git devscripts debhelper tcl8.6-dev autoconf \
  python3-dev python3-filelock python3-build python3-pip python3-pyasyncore python3-venv python3-setuptools \
  libboost-system-dev libboost-program-options-dev libboost-regex-dev libboost-filesystem-dev \
  libz-dev openssl patchelf wget

ADD https://github.com/flightaware/piaware_builder.git#v11.0 /src

WORKDIR /src
RUN ./sensible-build.sh trixie && cd package-trixie && dpkg-buildpackage -b --no-sign

FROM debian:13-slim

RUN --mount=type=bind,from=build,source=/src,target=/src apt-get update -yq && apt-get install -yq /src/piaware_11.0_*.deb

USER piaware

CMD ["/usr/bin/piaware", "-plainlog"]
