FROM debian:13-slim AS build

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update -yq && apt-get install -yq build-essential fakeroot debhelper librtlsdr-dev pkg-config libncurses5-dev libbladerf-dev libhackrf-dev liblimesuite-dev libsoapysdr-dev devscripts

ADD https://github.com/flightaware/dump1090.git#v11.0 /src

WORKDIR /src
RUN ./prepare-build.sh trixie && cd package-trixie && dpkg-buildpackage -b --no-sign

FROM debian:13-slim

RUN --mount=type=bind,from=build,source=/src,target=/src apt-get update -yq && apt-get install -yq /src/dump1090-fa_11.0_*.deb

USER dump1090

CMD ["/usr/share/dump1090-fa/start-dump1090-fa"]
