name: Build piaware

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/build-piaware.yml
      - .github/workflows/build-workflow.yml
      - piaware/**

jobs:
  build-piaware:
    permissions:
      packages: write
    uses: ./.github/workflows/build-workflow.yml
    with:
      path: piaware
      push: ${{ github.event_name == 'push' }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
