name: Build fr24feed

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/build-fr24feed.yml
      - fr24feed/**

jobs:
  build-fr24feed:
    permissions:
      packages: write
    uses: ./.github/workflows/build-workflow.yml
    with:
      path: fr24feed
      push: ${{ github.event_name == 'push' }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
