name: Build fr24feed

on:
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/build-fr24feed.yml
      - .github/workflows/build-workflow.yml
      - fr24feed/**

  push:
    branches: [main]
    paths:
      - .github/workflows/build-fr24feed.yml
      - .github/workflows/build-workflow.yml
      - fr24feed/**

  schedule:
    - cron: '0 0 * * 1' # every Monday at midnight

  workflow_dispatch:

jobs:
  build-fr24feed:
    permissions:
      packages: write
    uses: ./.github/workflows/build-workflow.yml
    with:
      path: fr24feed
      push: ${{ github.event_name == 'push' || github.event_name == 'schedule' }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
